### ISSUE TITLE
[Calendar] Add option to fill hours

### ISSUE THREAD

**Issue by gaborauth** [gaborauth/toolsboox-android#113]
**Is your feature request related to a problem? Please describe.**
I want to have a setup option to fill in the hours in the daily view.

**Describe the solution you'd like**
Prefilled hours on the daily view.

**Describe alternatives you've considered**

**Additional context**

**Comment by vasco9999** [comment]
There is a similar product that introduces the hours with PM/AM in front. People just have to strike what is not applicable. This could be done in a configuration option.
