### ISSUE TITLE
Shadowed weekend days

### ISSUE THREAD

**Issue by vasco9999** [gaborauth/toolsboox-android#119]
In the quartely planner could be nice to have the weekends shaded in light gray

**Comment by gaborauth** [comment]
In my case with my Note Air, it is shaded. What is the type of your device?

![image](https://user-images.githubusercontent.com/16724720/205696820-b0f85c3b-cf40-472d-b55a-98c34a807a34.png)

**Comment by vasco9999** [comment]
Mine is a Note Air as well.

I have reset the display optimizations, now it works.

Vasco Amaral

------------------------------------------
***@***.***
