### ISSUE TITLE
[General] Write permission request

### ISSUE THREAD

**Issue by gaborauth** [gaborauth/toolsboox-android#23]
**Describe the bug**
Storage write permission request probably missing on some devices...

**To Reproduce**
1. Go to 'Templates' plugin
2. Select 'Boxed days calendar'
3. Go to 'Export' tab
4. Missing Storage access right request

**Expected behavior**
n/a

**Screenshots**
n/a

**Device details:**
 - Device: Note Air2
 - OS: 2022-04-23_16-14_3.2.2
 - Version: latest

**Additional context**
https://www.facebook.com/groups/booxfansgroup/posts/1572776156488670/
https://www.reddit.com/r/Onyx_Boox/comments/y7azoy/comment/it0pu8h/

**Comment by krysinko** [comment]
Hi,
it was me who reported issue. I'm adding screens below. 
Later I reinstalled the version for 1.3.3.00 but it was still present.
![Screenshot_20221017-202407 1](https://user-images.githubusercontent.com/22563183/196254712-00cb9851-302a-47f2-981d-ad6ee7408ab1.png)
![Screenshot_20221017-202424 1](https://user-images.githubusercontent.com/22563183/196254784-fd57187f-ceb8-4fb7-bfee-e46e4db01575.png)
![Screenshot_20221017-202502 1](https://user-images.githubusercontent.com/22563183/196254856-58a305d1-bafa-460f-a869-d50b40bf32c8.png)

**Comment by gaborauth** [comment]
Would you try this apk? I've just moved the permission check to the dashboard. But I'm just guessing.

https://github.com/gaborauth/toolsboox-android/suites/8812188544/artifacts/400979435

**Comment by gaborauth** [comment]
Just merged to the main.

**Comment by gaborauth** [comment]
@krysinko is it still an issue on your device? I've redesigned the permission requests methods in the 1.5.0-01 version.

**Comment by MairaBelm** [comment]
I have suddenly started experiencing permission issues on exports with v1.5.7-02, even though the path is the same as before: /storage/emulated/0/Download/toolsBoox/noteTemplate/. Android is just granting permissions to media instead of files, and I could not find a way to add permissions to files in Android settings. I erased cache/data and reinstalled to no effect.

**Comment by gaborauth** [comment]
Hm... something strange happening with Note Air 2... :/

**Comment by MairaBelm** [comment]
Strange indeed. I uninstalled it again and re-instaled v1.5.6-00 directly from the apk, but I could not regain previous permissions. I am pretty sure it was working pre-1.5.7, though I did not try this feature until a couple of days ago. Now, on first launch in both versions, the app is asking for calendar access. Then comes the warning about Android 11, and that's all. 

I cannot remember if previous versions asked for file access. In case it is related somehow, I could never install the new apk on top of the previous one, always had to uninstall the old apk first. That is, until the app was available in Google Play (and then updated as expected).

**Comment by MairaBelm** [comment]
Yep, that did the trick! :-)
Sadly, the Boxed days template exported as January again (1.5.7-02-release).

**Comment by gaborauth** [comment]
> Yep, that did the trick! :-)

"Of course I knew. I just had no idea!" :)

> Sadly, the Boxed days template exported as January again (1.5.7-02-release).

The #80 not in the 1.5.7-02, it will be the part of the 1.5.8-xx.
