### ISSUE TITLE
Writing not possible on Note Air 3C (and Ultra C Pro)

### ISSUE THREAD

**Issue by duuudie** [gaborauth/toolsboox-android#305]
I´m not able to write with the pen anywhere. The app is reacting on the touches (also with the pen), but I cannot write in f.i. calender

1. Go to 'Calender'
2. Write in the Calender
3. Nothing happens. The screen remains as before

Expected behavior
I expect that I can write in the Calender app as well as in other views

Device details:
 - Device: Air Note 3 C
 - OS: 3.5
 - Version: 1.05.15-01

**Comment by torleif2** [comment]
Same problem on my Note air 3 C.

**Comment by JaspervdK** [comment]
Experiencing the same issue.

**Comment by gaborauth** [comment]
Guys, would you try this pre-release?

https://github.com/gaborauth/toolsboox-android/releases/tag/v1.5.15-02

**Comment by rolandd74** [comment]
Hi! No, unfortunately it's not working, same issue :-(

**Comment by zuhairzah** [comment]
I have tried the pre-release, but unfortunately it is not working.

**Comment by duuudie** [comment]
Same here, doesn't work on my device

**Comment by gaborauth** [comment]
I try to find some support from the Onyx. :(

**Comment by stetre76** [comment]
Hi - for what it's worth
doesn't work on the Tab Ultra C Pro either (not surprising, as it uses the same software/firmware as the Note Air 3 C)

**Comment by tama2402** [comment]
waiting for good news, my NA3C has same issue

**Comment by ricardoveramedina** [comment]
The same issue here :(

**Comment by Wiian16** [comment]
I am willing to build and run any new builds on my Note Air 3 C if you would like the logs.

**Comment by gaborauth** [comment]
> I am willing to build and run any new builds on my Note Air 3 C if you would like the logs.

It sounds great, would you join on Discord so we can discuss it there?

The invite link is https://discord.gg/S3sKsbmaSk

**Comment by gaborauth** [comment]
Guys! Thanks for 'Ghosts' user, there is a possible fix for the issue and here is an APK to install and test:

https://github.com/gaborauth/toolsboox-android/actions/runs/7599763176/artifacts/1183704738
