### ISSUE TITLE
[Calendar] Add navigate to notes button to Calendar

### ISSUE THREAD

**Issue by gaborauth** [gaborauth/toolsboox-android#57]
**Is your feature request related to a problem? Please describe.**
The down-to-up swipe conflicts with some user's settings in the 'Calendar' plugin.

**Describe the solution you'd like**
Add a button to the drawing toolbar to navigate to the notes of the calendar view.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by wanggit2** [comment]
if possible, add list of books being read and notes being created on that day (like the stock calendar memo).
