### ISSUE TITLE
[Calendar] Multiple note pages per Calendar view

### ISSUE THREAD

**Issue by gaborauth** [gaborauth/toolsboox-android#64]
**Is your feature request related to a problem? Please describe.**
Allow to use multiple pages of notes per day

**Describe the solution you'd like**
Swipe add a new notes page automatically.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by wanggit2** [comment]
Thank you! I was about to create suggestion for this. I really love this app of yours!
