### ISSUE TITLE
[Templates] Boxed days calendar template exports just January

### ISSUE THREAD

**Issue by MairaBelm** [gaborauth/toolsboox-android#80]
Exporting the template "Boxed days calendar" outputs a 30-page PDF for January, lacking day 31 maybe because it is using the current month (November) day count. In the exported PDF, the week days are correct for January, i. e. 1/1/2022 is Saturday (and not Tuesday as it would be for November). Tested with different "Generate with" settings in 1.5.6 and 1.5.7.

**Comment by gaborauth** [comment]
Oh, I forgot to update the month value in the template generator... it was fix and January... :)

Fixed: https://github.com/gaborauth/toolsboox-android/commit/537d52a536b0e7293e1101201aeb854b6481ea31
